---
# SPDX-FileCopyrightText: {{ copyright_date }}-present {{ maintainer_fullname }} <{{ maintainer_email }}>
#
# SPDX-License-Identifier: MIT
#
# Configuration for the Task runner
#
# See: https://taskfile.dev

version: "3"

includes:
  tf: tasks/tf

tasks:
  default:
    cmds:
      - task: list

  list:
    desc: List available tasks
    cmds:
      - task --list
